catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0
  vite-plus: 1.1.0
overrides:
  vite@*: "catalog:"
  "fflate@0.7.3": 0.7.5
patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
